### ISSUE TITLE
Check if geometry coordinates are defined anti clockwise and reorder if necessary 

### ISSUE THREAD

**Issue by indigocoral** [StemVibrations/gmsh_utils#19]
`def check_orientation(points):

    """

    Check if points are in clockwise or counter-clockwise order

    Parameters:

    -----------

    points: list

        The points to check

    """

    # calculate area of polygon

    area = 0

    for i in range(len(points) - 1):

        area += (points[i][0] * points[i+1][1]) - (points[i+1][0] * points[i][1])

    area += (points[-1][0] * points[0][1]) - (points[0][0] * points[-1][1])

    area = area / 2

    if area > 0:

        return "anti-clockwise"

    else:

        return "clockwise"`

**Comment by aronnoordam** [comment]
is solved in stem
